Небольшое улучшение скрипта сборки

diff --git a/trunk/linux-build b/trunk/linux-build
--- a/trunk/linux-build
+++ b/trunk/linux-build
@@ -1,12 +1,39 @@
 #!/bin/bash
 
-# %Id%
+debug="OFF"
+use_clang="OFF"
+verbose_build="OFF"
+opt_root_path="/tmp/mon"
+while getopts "dvchr:" opt
+do
+  case $opt in
+    d)
+      debug="ON"
+      ;;
+    c)
+      use_clang="ON"
+      ;;
+    v)
+      verbose_build="ON"
+      ;;
+    r)
+      opt_root_path=${OPTARG}
+      ;;
+    h)
+      echo "-d	Build debug"
+      echo "-v	Verbode build"
+      echo "-c	Build with clang"
+      echo "-r=/root/path	Setting root path for install and build"
+      echo "-h	This"
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      ;;
+  esac
+done
 
-. ./linux-environment
+. ./linux-environment "$opt_root_path"
 
-debug_off=${1:-"ON"}
-use_clang=${2:-"OFF"}
-verbose_build=${3:-"OFF"}
 current_path=$PWD
 function run_cmd
 {
@@ -30,7 +57,7 @@ function build()
   object_path="$current_path/$path"
   mkdir -p $object_build_path
   cd $object_build_path
-  run_cmd "CMake" "cmake -DCMAKE_INSTALL_PREFIX='$install_path' -DMON_VERBOSE_BUILD=$verbose_build -DBUILD_DEBUG=$debug_off -DMON_USE_CLANG=$use_clang  $object_path"
+  run_cmd "CMake" "cmake -DCMAKE_INSTALL_PREFIX='$install_path' -DMON_VERBOSE_BUILD=$verbose_build -DBUILD_DEBUG=$debug -DMON_USE_CLANG=$use_clang  $object_path"
   run_cmd "make" "make -j$build_threads"
   run_cmd "install" "make install"
   cd $build_path
